### ISSUE TITLE
@IsOptional() 데코레이터 사용

### ISSUE THREAD

**Issue by gyull92** [Jeongjiw00/NoAFK_nest#1]
위에서 이미 @IsOptional() 데코레이터로 선택적임을 명시하였으나 아래에서 password 속성에 옵셔널 체이닝을 추가한다면 동일한 의미를 가진 선언을 중복으로 하는 것이기에 @IsOptional() 데코레이터만 사용하는 것이 옳은 방법인 듯 합니다.

https://github.com/Jeongjiw00/NoAFK_nest/blob/d668fe706fea6bd784fdeed4399752e2555ea929/src/users/dto/update-user.dto.ts#L1-L24

**Comment by Jeongjiw00** [comment]
아이 이제 봤네요 감사합니다ㅎㅎ
